import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../scss/main.scss";
import LanguageWrapper from "@/wrappers/LanguageWrapper";
import SessionWrapper from "@/wrappers/SessionWrapper";
import FaviconWrapper from "@/wrappers/FaviconWrapper";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SimpliFlow",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <LanguageWrapper>
          {/* <FaviconWrapper> */}
          <body className={inter.className}>
            <Toaster />
            <div className="body-wrapper theme-dark">{children}</div>
          </body>
          {/* </FaviconWrapper> */}
        </LanguageWrapper>
      </html>
    </SessionWrapper>
  );
}
